name: MCX Mobile Access
on: [workflow_dispatch]

jobs:
  access:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.9.0
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        echo "Chromium version: $(chromium-browser --version)"
        echo "Chromedriver version: $(chromedriver --version)"
        
    - name: Create screenshots directory
      run: mkdir -p screenshots
        
    - name: Run script
      run: |
        python main.py
        
    - name: Verify screenshots exist
      run: |
        echo "Checking files:"
        ls -la screenshots/
        test -f screenshots/success.png || touch screenshots/empty_success.png
        test -f screenshots/error.png || touch screenshots/empty_error.png
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mcx-results
        path: screenshots/*
