name: Take MCX Screenshot

on:
  workflow_dispatch:

jobs:
  take-screenshot:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser
        pip install selenium

    - name: Run screenshot script
      run: python mcx_open.py

    - name: Upload screenshot
      uses: actions/upload-artifact@3d2f23882956b8e9e02cd9df6cd1f90bcf91b69d
      with:
        name: screenshot
        path: mcx_screenshot.png
