name: MCX Website Monitoring
on: [workflow_dispatch]

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: ubuntu:22.04
      options: --shm-size=2g

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python and Chrome
      run: |
        apt-get update
        apt-get install -y \
          python3.10 \
          python3-pip \
          chromium-browser \
          chromium-chromedriver \
          libgl1-mesa-glx \
          xvfb
        
        python3 -m pip install --upgrade pip
        pip install selenium==4.9.0 webdriver-manager

    - name: Create artifacts directory
      run: mkdir -p artifacts

    - name: Run MCX monitoring script
      run: |
        xvfb-run --auto-servernum python3 main.py
      env:
        DISPLAY: :99

    - name: Verify results
      run: |
        echo "Generated artifacts:"
        ls -la artifacts/
        if [ ! -f "artifacts/result.png" ]; then
          echo "::error::Screenshot was not generated!"
          exit 1
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mcx-monitoring-results
        path: |
          artifacts/*
          !artifacts/.gitkeep
        retention-days: 3
