name: MCX Homepage Access Monitor
on: [workflow_dispatch]

jobs:
  monitor:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    container:
      image: ubuntu:22.04
      options: --shm-size=1g

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python and Chrome
      run: |
        apt-get update
        apt-get install -y \
          python3 \
          python3-pip \
          chromium-browser \
          chromium-chromedriver
        
        python3 -m pip install --upgrade pip
        pip install selenium==4.9.0

    - name: Verify Chrome installation
      run: |
        echo "Chromium version: $(chromium-browser --version)"
        echo "Chromedriver version: $(chromedriver --version)"
        ls -la /usr/bin/chromedriver

    - name: Run MCX monitoring script
      run: python3 main.py

    - name: Evaluate results
      run: |
        if grep -q "✅ Successfully accessed MCX homepage" output.log; then
          echo "::notice::MCX homepage accessed successfully"
        elif grep -q "⛔ Access denied" output.log; then
          echo "::error::Access denied by MCX website"
          exit 1
        else
          echo "::error::Unexpected monitoring result"
          exit 1
        fi
