name: MCX Screenshot Test
on: [workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.9.0
        
    - name: Install Chrome with GPU support
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          chromium-browser \
          chromium-chromedriver \
          libgl1-mesa-glx \
          libgl1-mesa-dri
        echo "Chromium version: $(chromium-browser --version)"
        
    - name: Create screenshots directory
      run: mkdir -p screenshots
        
    - name: Run test
      run: |
        python main.py
        
    - name: Verify screenshots
      run: |
        echo "Screenshot contents:"
        ls -la screenshots/
        file screenshots/*.png
        
    - name: Upload results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: mcx-screenshots
        path: screenshots/*
