name: MCX Debugger
on: [workflow_dispatch]

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4  # Updated to v4
    
    - name: Set up Python
      uses: actions/setup-python@v5  # Updated to v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium==4.9.0
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser chromium-chromedriver
        
    - name: Run debugger
      run: |
        python main.py
        
    - name: Upload evidence
      uses: actions/upload-artifact@v4  # Updated to v4
      if: always()
      with:
        name: mcx-debug-artifacts
        path: |
          mcx_debug.png
          error.png
