name: MCX Access
on: [workflow_dispatch]

jobs:
  access:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo apt install -y ./google-chrome-stable_current_amd64.deb
        sudo ln -s /usr/bin/google-chrome-stable /usr/bin/chromium-browser
        
    - name: Run script
      run: |
        python main.py
        
    - name: Upload results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: mcx-results
        path: result.png
